SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";

CREATE DATABASE IF NOT EXISTS `musclewikison` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;
USE `musclewikison`;

CREATE TABLE `Exercises` (
  `exercise_name` varchar(64) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `muscle_group` varchar(64) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `difficult` varchar(64) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `equipment` varchar(64) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `guide` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `wikilink_musclegroup` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `key_exercise` varchar(64) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;



    INSERT INTO `Exercises` (`exercise_name`,`muscle_group`,`difficult`,`equipment`,`guide`,`key_exercise`,`wikilink_musclegroup`) VALUES ('Barbell Silverback Shrug', 'traps','Intermediate','barbell','Stand with your feet shoulder width apart holding the Barbell with both hands in front just past shoulder width.;Bend forward at the hips with a slight bend in your knees, keeping your back straight.;Engage your shoulder blades, as if you are trying to touch them together.;Release the shrug.','barbell-silverback-shrug','Trapezius');
    INSERT INTO `Exercises` (`exercise_name`,`muscle_group`,`difficult`,`equipment`,`guide`,`key_exercise`,`wikilink_musclegroup`) VALUES ('Dumbbell Seated Shrug', 'traps','Beginer','dumbbell','Sit on a bench with dumbbells in both hands, palms facing your body, back straight.;Elevate your shoulders and hold the contracted position at the apex of the motion.;Slowly lower your shoulders back to starting position.','dumbbell-seated-shrug','Trapezius');
    INSERT INTO `Exercises` (`exercise_name`,`muscle_group`,`difficult`,`equipment`,`guide`,`key_exercise`,`wikilink_musclegroup`) VALUES ('Long Lever Plank', 'abdominals','Advanced','no','Start in a hand plank position and walk your hands further out until your ears are between your biceps.;Hold in this position for the allotted amount of time.;Make sure you keep a flat back for the whole set.','long-lever-plank','Abdomen#Muscles');
    INSERT INTO `Exercises` (`exercise_name`,`muscle_group`,`difficult`,`equipment`,`guide`,`key_exercise`,`wikilink_musclegroup`) VALUES ('Hanging Knee Raises', 'abdominals','Beginer','fitness-workout-station','Grab the bar and hang, your body still and your legs straight.;Slowly draw your knees up to your chest;Once you have raised your knees as high as possible, lower your legs and repeat. Duration of these movements should be slow so that you do not utilize momentum, enabling you to get the most out of the exercise.;Duration of these movements should be slow so that you do not utilize momentum, enabling you to get the most out of the exercise.','hanging-knee-raises','Abdomen#Muscles');
    INSERT INTO `Exercises` (`exercise_name`,`muscle_group`,`difficult`,`equipment`,`guide`,`key_exercise`,`wikilink_musclegroup`) VALUES ('Chin Ups', 'biceps','Intermediate','fitness-workout-station','Grab the bar shoulder width apart with a supinated grip (palms facing you).;With your body hanging and arms fully extended, pull yourself up until your chin is past the bar.;Slowly return to starting position. Repeat.','chin-ups','Biceps');
    INSERT INTO `Exercises` (`exercise_name`,`muscle_group`,`difficult`,`equipment`,`guide`,`key_exercise`,`wikilink_musclegroup`) VALUES ('Barbell Curl', 'biceps','Beginer','barbell','While holding the upper arms stationary, curl the weights forward while contracting the biceps as you breathe out.;Continue the movement until your biceps are fully contracted and the bar is at shoulder level.;Hold the contracted position for a second and squeeze the biceps hard.;Slowly bring the weight back down to the starting position.','barbell-curl','Biceps');
    INSERT INTO `Exercises` (`exercise_name`,`muscle_group`,`difficult`,`equipment`,`guide`,`key_exercise`,`wikilink_musclegroup`) VALUES ('Machine Standing Calf Raises', 'calves','Beginer','machine-standing-calf-raises','Adjust the machine in accordance with your height and place your shoulders underneath the padded lever.;The balls of your feet should be supporting your weight on the calve block, your heels extending off of it.;Extend your heels upwards while keeping your knees stationary, and pause at the contracted position.;Slowly return to the starting position. Repeat.','machine-standing-calf-raises','Calf_(leg)');
    INSERT INTO `Exercises` (`exercise_name`,`muscle_group`,`difficult`,`equipment`,`guide`,`key_exercise`,`wikilink_musclegroup`) VALUES ('Barbell Calf Raises', 'calves','Intermediate','barbell','Place the bar on your back.;Start with feet flat on the ground.;Extend your heels upwards while keeping your knees stationary, and pause at the contracted position.;Slowly return to the starting position. Repeat.','barbell-calf-raises','Calf_(leg)');
    INSERT INTO `Exercises` (`exercise_name`,`muscle_group`,`difficult`,`equipment`,`guide`,`key_exercise`,`wikilink_musclegroup`) VALUES ('Barbell Bench Press', 'chest','Intermediate','barbell','Lay flat on the bench with your feet on the ground. With straight arms unrack the bar.;Lower the bar to your mid chest.;Raise the bar until you have locked your elbows.','barbell-bench-press','Thorax');
    INSERT INTO `Exercises` (`exercise_name`,`muscle_group`,`difficult`,`equipment`,`guide`,`key_exercise`,`wikilink_musclegroup`) VALUES ('Push Up', 'chest','Beginer','no','Place your hands firmly on the ground, directly under shoulders.;Flatten your back so your entire body is straight and slowly lower your body.;Draw shoulder blades back and down, keeping elbows tucked close to your body.;Exhale as you push back to the starting position.','barbell-calf-raises','Thorax');
    INSERT INTO `Exercises` (`exercise_name`,`muscle_group`,`difficult`,`equipment`,`guide`,`key_exercise`,`wikilink_musclegroup`) VALUES ('Chin Ups', 'forearms','Intermediate','fitness-workout-station','Grab the bar shoulder width apart with a supinated grip (palms facing you).;With your body hanging and arms fully extended, pull yourself up until your chin is past the bar.;Slowly return to starting position. Repeat.','chin-ups','Forearm#Muscles');
    INSERT INTO `Exercises` (`exercise_name`,`muscle_group`,`difficult`,`equipment`,`guide`,`key_exercise`,`wikilink_musclegroup`) VALUES ('Dumbbell Wrist Curl', 'forearms','Beginer','dumbbell','Grip the dumbbell with your palm facing upwards with your forearm rested against the bench.;Slowly draw your knees up to your chest.;Slowly curl your wrist upwards in a semicircular motion.;Return to starting position and repeat.','dumbbell-wrist-curl','Forearm#Muscles');
    INSERT INTO `Exercises` (`exercise_name`,`muscle_group`,`difficult`,`equipment`,`guide`,`key_exercise`,`wikilink_musclegroup`) VALUES ('Hand Side Plank', 'obliques','Intermediate','no','Press your hand into the ground and pick up your hip off the ground.;Open your chest and maintain this position for the allotted amount of time.','hand-side-plank','Abdominal_external_oblique_muscle');
    INSERT INTO `Exercises` (`exercise_name`,`muscle_group`,`difficult`,`equipment`,`guide`,`key_exercise`,`wikilink_musclegroup`) VALUES ('Barbell Landmine Side Bend', 'obliques','Intermediate','barbell','Stand straight and hold the end of the Barbell.;Keep your hips and shoulders facing forward, bend to one side slowly.;Return to the upright position.;Switch hands and repeat.','barbell-landmine-side-bend','Abdominal_external_oblique_muscle');
    INSERT INTO `Exercises` (`exercise_name`,`muscle_group`,`difficult`,`equipment`,`guide`,`key_exercise`,`wikilink_musclegroup`) VALUES ('Barbell Squat', 'quads','Intermediate','barbell','Stand with your feet shoulder-width apart. Maintain the natural arch in your back, squeezing your shoulder blades and raising your chest.;Grip the bar across your shoulders and support it on your upper back. Unwrack the bar by straightening your legs, and take a step back.;Bend your knees as you lower the weight without altering the form of your back until your hips are below your knees.;Raise the bar back to starting position, lift with your legs and exhale at the top.','barbell-squat','Quadriceps');
    INSERT INTO `Exercises` (`exercise_name`,`muscle_group`,`difficult`,`equipment`,`guide`,`key_exercise`,`wikilink_musclegroup`) VALUES ('Machine Leg Extension', 'quads','Intermediate','leg-machine','Sit on the machine with your back against the cushion and adjust the machine you are using so that your knees are at a 90 degree angle at the starting position.;Raise the weight by extending your knees outward, then lower your leg to the starting position. Both movements should be done in a slow, controlled motion.','machine-leg-extension','Quadriceps');
    INSERT INTO `Exercises` (`exercise_name`,`muscle_group`,`difficult`,`equipment`,`guide`,`key_exercise`,`wikilink_musclegroup`) VALUES ('Barbell Overhead Press', 'shoulders','Intermediate','barbell','Take a roughly shoulder width grip. There should be a straight line from your elbow to fist (vertical forearms).;Pull your chin back and press the weight toward the ceiling by extending at the elbow joint and flexing at the shoulder joint.;Press until your elbows are extended and push your head forward slightly.;Return to the start position with control.;Pulling your chin back to allow the bar to pass your face safely.','barbell-overhead-press','Shoulder');
	INSERT INTO `Exercises` (`exercise_name`,`muscle_group`,`difficult`,`equipment`,`guide`,`key_exercise`,`wikilink_musclegroup`) VALUES ('Dumbbell Seated Overhead Press', 'shoulders','Beginer','dumbbell','Sit on a bench with back support. Raise the dumbbells to shoulder height with your palms forward.;Raise the dumbbells upwards and pause at the contracted position.;Lower the weights back to starting position.','dumbbell-seated-overhead-press','Shoulder');
